import "~/styles/globals.css";

import { canela, vintageBrush } from "~/fonts/fonts";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${canela.variable} ${vintageBrush.variable}`}>
      <body className="font-canela">
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
